CanalTP\MttBundle\Entity\Area:
    type: entity
    table: mtt.area
    repositoryClass: CanalTP\MttBundle\Entity\AreaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            length: 255
        stopPoints:
            type: array
            column: stop_points
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        perimeter_area_idx:
            columns: [ label, perimeter_id ]
    manyToOne:
        perimeter:
            targetEntity: CanalTP\NmmPortalBundle\Entity\Perimeter
            joinColumn:
                name: perimeter_id
                referencedColumnName: per_id
    oneToMany:
        areasPdf:
            targetEntity: AreaPdf
            mappedBy: area
    lifecycleCallbacks: {  }
