CanalTP\MttBundle\Entity\DistributionList:
    type: entity
    table: mtt.distribution_list
    repositoryClass: CanalTP\MttBundle\Entity\DistributionListRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        externalRouteId:
            type: string
            length: 255
            column: external_route_id
        includedStops:
            type: array
            column: included_stops
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        perimeter_external_route_idx:
            columns: [ perimeter_id, external_route_id ]
    manyToOne:
        perimeter:
            targetEntity: CanalTP\NmmPortalBundle\Entity\Perimeter
            inversedBy: mtt.ditribution_lists
            joinColumn:
                name: perimeter_id
                referencedColumnName: per_id
