CanalTP\MttBundle\Entity\LayoutConfig:
    type: entity
    table: mtt.layout_config
    repositoryClass: CanalTP\MttBundle\Entity\LayoutConfigRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: 255
        calendarStart:
            type: integer
            column: calendar_start
        calendarEnd:
            type: integer
            column: calendar_end
        previewPath:
            type: string
            length: 255
            column: preview_path
            nullable: true
        notesMode:
            type: integer
            column: notes_mode
        notesColors:
            type: array
            column: notes_colors
        notesType:
            type: string
            column: notes_type
        horizontalMerge:
            type: boolean
            column: horizontal_merge
        verticalMerge:
            type: boolean
            column: vertical_merge
        verticalMergeOffset:
            type: integer
            column: vertical_merge_offset
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        lineConfigs:
            targetEntity: LineConfig
            mappedBy: layoutConfig
            cascade: ["persist"]
    manyToOne:
        layout:
            targetEntity: Layout
            inversedBy: layoutConfigs
            joinColumn:
                name: layout_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
