CanalTP\MttBundle\Entity\LayoutConfig:
    type: entity
    table: mtt.layout_config
    repositoryClass: CanalTP\MttBundle\Entity\LayoutConfigRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: 255
        calendatStart:
            type: integer
            column: calendat_start
        calendarEnd:
            type: integer
            column: calendar_end
        notesMode:
            type: integer
            column: notes_mode
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        lineConfigs:
            targetEntity: LineConfig
            mappedBy: layout
    manyToMany:
        networks:
            targetEntity: CanalTP\MttBundle\Entity\Network
            mappedBy: layouts
    lifecycleCallbacks: {  }
