<?php

namespace CanalTP\MethBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
    public function findByLineAndDomId($lineId, $domId)
    {
        return $this->findOneBy(array('line' => $lineId, 'domId' => $domId));
    }
}
