<?php

namespace CanalTP\MethBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistributionListRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionListRepository extends EntityRepository
{
    public function sortSchedules($schedules, $timetable)
    {
        $distributionList = $this->findOneByTimetable($timetable);
        $sortedSchedules = array();
        $sortedSchedules['included'] = array();
        $sortedSchedules['excluded'] = array();
        
        if (empty($distributionList))
        {
            $sortedSchedules['included'] = $schedules;
        }
        else
        {
            $includedStops = $distributionList->getIncludedStops();
            foreach($schedules as $schedule)
            {
                if (in_array($schedule->stop_point->id, $includedStops))
                {
                    $sortedSchedules['included'][] = $schedule;
                }
                else
                {
                    $sortedSchedules['excluded'][] = $schedule;
                }
            }
        }
        return $sortedSchedules;
    }
}
