<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CanalTP\NmmPortalBundle\Entity\Customer;

/**
 * LayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutRepository extends EntityRepository
{
}
