<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LayoutConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutConfigRepository extends EntityRepository
{
    // TODO: Add Translator service.
    public function orientationName($orientationType)
    {
        $name = 'Unknown';

        switch ($orientationType) {
            case Layout::ORIENTATION_LANDSCAPE:
                $name = 'Landscape';
                break;
        }
        return ($name);
    }
}
