<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CanalTP\NmmPortalBundle\Entity\Customer;

/**
 * LayoutConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutConfigRepository extends EntityRepository
{
    public function findLayoutConfigByCustomer(Customer $customer)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('lc', 'l', 'c')
            ->from('CanalTPMttBundle:LayoutConfig', 'lc')
            ->join('lc.layout', 'l')
            ->join('l.customers', 'c')
            ->where('c.customer = :customer')
            ->setParameter('customer', $customer)
            ->getQuery();

        return $query->getResult();
    }
}
