<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CanalTP\NmmPortalBundle\Entity\Customer;

/**
 * LayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutRepository extends EntityRepository
{
    public function findLayoutByCustomer(Customer $customer)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('l', 'c')
            ->from('CanalTPMttBundle:Layout', 'l')
            ->join('l.customers', 'c')
            ->where('c.customer = :customer')
            ->setParameter('customer', $customer)
            ->getQuery();

        return $query->getResult();
    }
}
