<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LineConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineConfigRepository extends EntityRepository
{
    public function getLineConfigByExternalLineIdAndSeason($externalLineId, $season)
    {
        $lineConfig = null;
        $lineConfig = $this->findOneBy(
            array(
                'externalLineId' => $externalLineId,
                'season' => $season->getId()
            )
        );

        if (!$lineConfig) {
            $lineConfig = new LineConfig();

            $lineConfig->setSeason($season);
        }

        return ($lineConfig);
    }
}
