<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetworkRepository extends EntityRepository
{
    public function addUserToNetwork($userId, $networkId)
    {
        $conn = $this->getEntityManager()->getConnection();
        $conn->insert(
            ' mtt.users_networks',
            array(
                'network_id' => $networkId,
                'user_id' => $userId,
            )
        );
    }

    public function deleteUserNetworks($userId)
    {
        $conn = $this->getEntityManager()->getConnection();
        $conn->delete(
            ' mtt.users_networks',
            array(
                'user_id' => $userId,
            )
        );
    }
}
