<?php

namespace CanalTP\MethBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteRepository extends EntityRepository
{
    
    public function getRoute($externalId)
    {
        $route = $this->findOneByExternalId($externalId);
        // do we have a record for this route?
        if (empty($route)) {
            $route = $this->insertRoute($externalId);
        }
        return $route;
    }
    
    private function insertRoute($externalId)
    {
        $route = new Route();
        $route->setExternalId($externalId);
        $this->getEntityManager()->persist($route);
        
        return $route;
    }
}
