<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
    // used by webservice
    public function findSeasonForDateTime($dateTime)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                    ->select("s.id")
                    ->from("CanalTPMttBundle:Season", "s")
                    ->where("s.published = TRUE")
                    ->andWhere("s.startDate <= '".$dateTime->format("Y-m-d H:i:s")."'")
                    ->andWhere("s.endDate >= '".$dateTime->format("Y-m-d H:i:s")."'")
                    ->getQuery();

        return $query->getResult();
    }
}
