<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
    public function getSeasonByNetworkIdAndSeasonId($networkId, $seasonId)
    {
        $season = null;
        if ($seasonId) {
            $season = $this->getEntityManager()->getRepository('CanalTPMttBundle:Season')->find($seasonId);
        }
        if ($season) {
            $networkRepository = $this->getEntityManager()->getRepository('CanalTPMttBundle:Network');
            $season = new Season();

            $season->setNetwork($networkRepository->findByExternalId($networkId));
        }
        return ($season);
    }
}
