<?php

namespace CanalTP\MethBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StopPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopPointRepository extends EntityRepository
{
    public function updatePdfGenerationDate($lineId, $stopPointNavitiaId)
    {
        $stopPoint = $this->getStopPoint($lineId, $stopPointNavitiaId);
        
        $stopPoint->setPdfGenerationDate(new \DateTime());
        $this->getEntityManager()->persist($stopPoint);
        $this->getEntityManager()->flush();
    }
    
    public function getStopPoint($lineId, $stopPointNavitiaId)
    {
        $stopPoint = $this->findOneBy(array('line' => $lineId, 'navitiaId' => $stopPointNavitiaId));
        // do this stop_point exists?
        if (empty($stopPoint)) {
            $stopPoint = $this->insertStopPoint($lineId, $stopPointNavitiaId);
        }
        return $stopPoint;
    }
    
    private function insertStopPoint($lineId, $stopPointNavitiaId)
    {
        $stopPoint = new StopPoint();
        $line = $this->getEntityManager()->getPartialReference(
            'CanalTP\MethBundle\Entity\Line',
            $lineId
        );
        $stopPoint->setNavitiaId($stopPointNavitiaId);
        $stopPoint->setLine($line);
        $this->getEntityManager()->persist($stopPoint);
        
        return $stopPoint;
    }
    
    public function hasPdfUpToDate($stopPointNavitiaId, $lineId)
    {
        $stopPoint = $this->findOneBy(array('line' => $lineId, 'navitiaId' => $stopPointNavitiaId));
        // var_dump($stopPoint->getPdfGenerationDate(), $stopPoint->getLastModified(), $stopPoint->getLine()->getLastModified());die;
        if (
        // no stop point
        empty($stopPoint) ||
        // no pdf generated yet => return FALSE
        $stopPoint->getPdfGenerationDate() == NULL || 
        // line was modified after pdf generation
        $stopPoint->getLine()->getLastModified() > $stopPoint->getPdfGenerationDate() ||
        // stop was modified after pdf generation
        $stopPoint->getLastModified() > $stopPoint->getPdfGenerationDate()
        )
        {
            return FALSE;
        }
        else
        {
            return TRUE;
        }
    }
}
