<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StopPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopPointRepository extends EntityRepository
{
    public function getBlocks($stopPoint, $timetable)
    {
        $result = $this->getEntityManager()->getRepository('CanalTPMttBundle:Block')->findBy(
            array(
                'stopPoint' => $stopPoint->getId(),
                'timetable' => $timetable->getId()
            )
        );

        return $result;
    }

    public function updatePdfGenerationInfos($externalStopPointId, $timetable, $hash)
    {
        $stopPoint = $this->getStopPoint($externalStopPointId, $timetable);

        $stopPoint->setPdfGenerationDate(new \DateTime());
        $stopPoint->setPdfHash($hash);
        $this->getEntityManager()->flush($stopPoint);
    }

    public function getStopPoint($externalStopPointId, $timetable)
    {
        $stopPoint = $this->findOneBy(
            array(
                'externalId' => $externalStopPointId,
                'timetable' => $timetable->getId(),
            )
        );

        // do this stop_point exists?
        if (empty($stopPoint)) {
            $stopPoint = $this->insertStopPoint(
                $externalStopPointId,
                $timetable
            );
        }

        return $stopPoint;
    }

    private function insertStopPoint($externalStopPointId, $timetable)
    {
        $stopPoint = new StopPoint();
        $stopPoint->setExternalId($externalStopPointId);
        $stopPoint->setTimetable($timetable);
        $this->getEntityManager()->persist($stopPoint);

        return $stopPoint;
    }

    private function isUpToDate($pdfGenerationDate, $blocks)
    {
        foreach ($blocks as $block) {
            if ($block->getUpdated() != null && $block->getUpdated() > $pdfGenerationDate) {
                return (false);
            }
        }

        return (true);
    }

    public function hasPdfUpToDate($stopPoint, $timetable)
    {
        $timetableRepo = $this->getEntityManager()->getRepository('CanalTPMttBundle:Timetable');

        // no stop point
        // no pdf generated yet => return FALSE
        return (!$stopPoint->getPdfGenerationDate() == null ||
            // timetable was modified after pdf generation
            ($this->isUpToDate(
                $stopPoint->getPdfGenerationDate(),
                $timetableRepo->findBlocksByTimetableIdOnly($timetable->getId())
            ) &&
            $this->isUpToDate($stopPoint->getPdfGenerationDate(), $stopPoint->getBlocks()))
        );
    }
}
