<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StopTimetableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopTimetableRepository extends EntityRepository
{
    /*
     * init stopTimetable object, if not found in db create an entity
     */
    public function getStopTimetableByRouteExternalId($externalRouteId, $lineConfig)
    {
        $stopTimetable = null;
        if ($lineConfig != null) {
            $stopTimetable = $this->findOneBy(
                array(
                    'externalRouteId' => $externalRouteId,
                    'lineConfig' => $lineConfig->getId(),
                )
            );
        }
        // not found then insert it
        if (empty($stopTimetable)) {
            $stopTimetable = new StopTimetable();
            $stopTimetable->setExternalRouteId($externalRouteId);
            $stopTimetable->setLineConfig($lineConfig);

            $this->getEntityManager()->persist($stopTimetable);
            $this->getEntityManager()->flush();
        }

        return $stopTimetable;
    }

    /*
     * Return blocks defined for this stopTimetable on route level
     */
    public function findBlocksByStopTimetableIdOnly($stopTimetableId)
    {
        $result = $this->getEntityManager()->getRepository('CanalTPMttBundle:Block')->findBy(
            array(
                'stopPoint' => null,
                'stopTimetable' => $stopTimetableId
            ),
            array('domId' => 'ASC')
        );

        return $result;
    }

    /**
     * Does this stopTimetable have a task under progress?
     * @return boolean
     */
    public function hasAmqpTasksRunning($stopTimetableId, $taskTypeId = AmqpTask::AREA_PDF_GENERATION_TYPE)
    {
        $result = $this->getEntityManager()->getRepository('CanalTPMttBundle:AmqpTask')->findBy(
            array(
                'objectId' => $stopTimetableId,
                'status' => AmqpTask::LAUNCHED_STATUS,
                'typeId' => $taskTypeId
            )
        );

        return count($result) > 0;
    }
}
