<?php

namespace CanalTP\MttBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimetableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimetableRepository extends EntityRepository
{
    /*
     * init timetable object, if not found in db create an entity
     */
    public function getTimetableByRouteExternalId($externalRouteId, $lineConfig)
    {
        $timetable = null;
        if ($lineConfig != null) {
            $timetable = $this->findOneBy(
                array(
                    'externalRouteId' => $externalRouteId,
                    'line_config' => $lineConfig->getId(),
                )
            );
        }
        // not found then insert it
        if (empty($timetable)) {
            $timetable = new Timetable();
            $timetable->setExternalRouteId($externalRouteId);
            $timetable->setLineConfig($lineConfig);

            $this->getEntityManager()->persist($timetable);
            $this->getEntityManager()->flush();
        }

        return $timetable;
    }

    /*
     * Return blocks defined for this timetable on route level
     */
    public function findBlocksByTimetableIdOnly($timetableId)
    {
        $result = $this->getEntityManager()->getRepository('CanalTPMttBundle:Block')->findBy(
            array(
                'stopPoint' => null,
                'timetable' => $timetableId
            ),
            array('domId' => 'ASC')
        );

        return $result;
    }

    /**
     * Does this timetable have a task under progress?
     * @return boolean
     */
    public function hasAmqpTasksRunning($timetableId, $taskTypeId = AmqpTask::AREA_PDF_GENERATION_TYPE)
    {
        $result = $this->getEntityManager()->getRepository('CanalTPMttBundle:AmqpTask')->findBy(
            array(
                'objectId' => $timetableId,
                'status' => AmqpTask::LAUNCHED_STATUS,
                'typeId' => $taskTypeId
            )
        );

        return count($result) > 0;
    }
}
